namespace HTMLBuilder.Ui;

internal static class Localizer
{
    public const string English = "en";
    public const string Spanish = "es";

    private static string currentLanguage = English;

    public static string CurrentLanguage
    {
        get => currentLanguage;
        set => currentLanguage = NormalizeLanguage(value);
    }

    public static bool IsSpanish => CurrentLanguage == Spanish;

    public static string NormalizeLanguage(string? language) =>
        string.Equals(language, Spanish, StringComparison.OrdinalIgnoreCase) ? Spanish : English;

    public static string T(string key) =>
        IsSpanish && SpanishStrings.TryGetValue(key, out var spanish)
            ? spanish
            : EnglishStrings.TryGetValue(key, out var english)
                ? english
                : key;

    public static string FieldLabel(string text) =>
        IsSpanish ? text : FieldLabels.GetValueOrDefault(text, text);

    public static string FieldHelp(string text) =>
        IsSpanish ? text : FieldHelps.GetValueOrDefault(text, text);

    private static readonly Dictionary<string, string> EnglishStrings = new(StringComparer.Ordinal)
    {
        ["menu.file"] = "&File",
        ["menu.new"] = "&New document",
        ["menu.open"] = "&Open HTML...",
        ["menu.save"] = "&Save HTML document...",
        ["menu.preferences"] = "&Preferences...",
        ["menu.exit"] = "Exit",
        ["menu.document"] = "&Document",
        ["menu.properties"] = "&Document properties...",
        ["menu.element"] = "&Element",
        ["menu.addChild"] = "Add &child element...",
        ["menu.editElement"] = "&Edit element...",
        ["menu.deleteElement"] = "Delete element",
        ["menu.moveUp"] = "Move up",
        ["menu.moveDown"] = "Move down",
        ["menu.attributes"] = "&Attributes",
        ["menu.addAttribute"] = "Add or edit attribute...",
        ["menu.removeAttribute"] = "Remove attribute...",
        ["menu.view"] = "&View",
        ["menu.refreshPreview"] = "Refresh preview",
        ["menu.openBrowser"] = "Open in browser",
        ["menu.copyHtml"] = "Copy HTML",
        ["menu.help"] = "&Help",
        ["menu.about"] = "About this application",
        ["access.tree"] = "Document structure tree",
        ["access.preview"] = "Generated HTML preview",
        ["dialog.newConfirm"] = "Create a new document and discard the current one?",
        ["title.newDocument"] = "New document",
        ["dialog.openTitle"] = "Open HTML",
        ["dialog.openFilter"] = "HTML (*.html;*.htm)|*.html;*.htm|All files (*.*)|*.*",
        ["dialog.openError"] = "Could not open the file",
        ["dialog.saveTitle"] = "Save HTML",
        ["dialog.saveFilter"] = "HTML (*.html)|*.html",
        ["dialog.defaultFileName"] = "page.html",
        ["dialog.saveError"] = "Could not save the file",
        ["msg.noChildren"] = "The {0} tag cannot contain child elements.",
        ["title.invalidStructure"] = "Invalid structure",
        ["title.addChild"] = "Add child element",
        ["msg.structuralNotEditable"] = "The html, head, and body structural nodes are not edited directly. Use Document > Properties for the language and title.",
        ["title.documentStructure"] = "Document structure",
        ["title.editElement"] = "Edit element",
        ["msg.structuralNotDelete"] = "The html, head, or body structural nodes cannot be deleted.",
        ["msg.deleteConfirm"] = "Delete {0}?",
        ["title.confirmDelete"] = "Confirm deletion",
        ["msg.cannotMove"] = "Cannot move any further in that direction.",
        ["title.moveElement"] = "Move element",
        ["msg.noEditableAttributes"] = "The {0} tag has no editable attributes in this editor.",
        ["title.noAttributes"] = "No attributes",
        ["msg.noAttributesOnElement"] = "The selected element has no attributes.",
        ["msg.copiedHtml"] = "The HTML was copied to the clipboard.",
        ["title.copyHtml"] = "Copy HTML",
        ["dialog.previewFileName"] = "current-document.html",
        ["dialog.browserError"] = "Could not open the preview in the browser",
        ["about.text"] = "HTMLBuilder\r\n\r\nDesktop application for creating structured, accessible, and maintainable HTML pages.",
        ["button.save"] = "Save changes",
        ["button.cancel"] = "Cancel",
        ["button.close"] = "Close",
        ["button.removeAttribute"] = "Remove attribute",
        ["button.addAttribute"] = "Add or edit attribute",
        ["label.htmlTag"] = "HTML tag",
        ["label.tagFields"] = "Fields for this tag",
        ["label.textContent"] = "Text content",
        ["label.validAttributes"] = "Valid attributes",
        ["label.attributeName"] = "Attribute name",
        ["label.value"] = "Value",
        ["label.documentTitle"] = "Page title",
        ["label.language"] = "Language",
        ["label.requiredSuffix"] = "{0} required",
        ["hint.noSpecialFields"] = "This tag does not require special fields. You can add valid attributes below.",
        ["hint.parent.none"] = "The {0} tag does not allow new child elements.",
        ["hint.parent.one"] = "The {0} tag only allows the {1} child.",
        ["hint.parent.many"] = "The {0} tag allows {1} valid child types.",
        ["access.tagCombo"] = "HTML tag. Press F1 for help about the selected tag.",
        ["access.parentHint"] = "Information about the allowed structure",
        ["access.textContent"] = "Text content",
        ["access.tagFields"] = "Tag fields",
        ["access.attributeList"] = "Element attributes",
        ["access.attributeName"] = "Attribute name. Press F1 for help about the selected attribute.",
        ["access.attributeValue"] = "Attribute value",
        ["access.presetValue"] = "Preset attribute value",
        ["access.selectedAttributes"] = "Attributes of the selected element",
        ["msg.invalidTag"] = "The selected tag is not valid.",
        ["title.invalidTag"] = "Invalid tag",
        ["msg.childNotAllowed"] = "The {0} tag cannot be added inside {1}.",
        ["msg.attributeNotAllowed"] = "The {0} attribute is not valid for the {1} tag.",
        ["title.attributeNotAllowed"] = "Attribute not allowed",
        ["msg.requiredField"] = "The {0} tag requires the {1} field.",
        ["title.requiredField"] = "Required field",
        ["msg.invalidMeta"] = "The meta tag must use charset, or name together with content.",
        ["title.incompleteMeta"] = "Incomplete meta",
        ["msg.anchorNeedsText"] = "The a tag needs visible text that explains the destination.",
        ["title.requiredText"] = "Required text",
        ["msg.noSelectedAttribute"] = "No attribute is selected.",
        ["title.editAttribute"] = "Edit attribute",
        ["msg.tagNoAttributes"] = "The {0} tag has no editable attributes.",
        ["msg.invalidAttributeName"] = "The attribute name is not valid.",
        ["title.invalidAttribute"] = "Invalid attribute",
        ["msg.attributeNeedsValue"] = "The {0} attribute needs a value.",
        ["title.requiredValue"] = "Required value",
        ["hint.booleanAttribute"] = "This attribute is boolean and does not need a value.",
        ["title.documentProperties"] = "Document properties",
        ["default.untitled"] = "Untitled document",
        ["default.imported"] = "Imported HTML",
        ["help.tag.title"] = "{0} tag help",
        ["help.attribute.title"] = "{0} attribute help",
        ["help.tag.access"] = "Help for the selected tag",
        ["help.attribute.access"] = "Help for the selected attribute",
        ["help.tag.label"] = "Tag: {0}",
        ["help.attribute.label"] = "Attribute: {0}",
        ["help.what"] = "What it does:",
        ["help.accessibility"] = "Common accessibility parameters:",
        ["help.values"] = "Accepted values:",
        ["help.advice"] = "Tip:",
        ["preferences.title"] = "Preferences",
        ["preferences.language"] = "Interface language",
        ["preferences.english"] = "English",
        ["preferences.spanish"] = "Spanish",
        ["preferences.restartless"] = "The interface will update immediately.",
        ["language.title"] = "Choose your language",
        ["language.message"] = "Select the interface language for HTMLBuilder.",
        ["language.english"] = "English",
        ["language.spanish"] = "Spanish"
    };

    private static readonly Dictionary<string, string> SpanishStrings = new(StringComparer.Ordinal)
    {
        ["menu.file"] = "&Archivo",
        ["menu.new"] = "&Nuevo documento",
        ["menu.open"] = "&Abrir HTML...",
        ["menu.save"] = "&Guardar documento HTML...",
        ["menu.preferences"] = "&Preferencias...",
        ["menu.exit"] = "Salir",
        ["menu.document"] = "&Documento",
        ["menu.properties"] = "&Propiedades del documento...",
        ["menu.element"] = "&Elemento",
        ["menu.addChild"] = "Agregar elemento &hijo...",
        ["menu.editElement"] = "&Editar elemento...",
        ["menu.deleteElement"] = "Eliminar elemento",
        ["menu.moveUp"] = "Mover hacia arriba",
        ["menu.moveDown"] = "Mover hacia abajo",
        ["menu.attributes"] = "&Atributos",
        ["menu.addAttribute"] = "Agregar o modificar atributo...",
        ["menu.removeAttribute"] = "Quitar atributo...",
        ["menu.view"] = "&Vista",
        ["menu.refreshPreview"] = "Actualizar vista previa",
        ["menu.openBrowser"] = "Abrir en navegador",
        ["menu.copyHtml"] = "Copiar HTML",
        ["menu.help"] = "A&yuda",
        ["menu.about"] = "Acerca de la aplicación",
        ["access.tree"] = "Árbol de estructura del documento",
        ["access.preview"] = "Vista previa del HTML generado",
        ["dialog.newConfirm"] = "¿Crear un documento nuevo y descartar el actual?",
        ["title.newDocument"] = "Nuevo documento",
        ["dialog.openTitle"] = "Abrir HTML",
        ["dialog.openFilter"] = "HTML (*.html;*.htm)|*.html;*.htm|Todos los archivos (*.*)|*.*",
        ["dialog.openError"] = "No se pudo abrir el archivo",
        ["dialog.saveTitle"] = "Guardar HTML",
        ["dialog.saveFilter"] = "HTML (*.html)|*.html",
        ["dialog.defaultFileName"] = "pagina.html",
        ["dialog.saveError"] = "No se pudo guardar el archivo",
        ["msg.noChildren"] = "La etiqueta {0} no puede contener elementos hijos.",
        ["title.invalidStructure"] = "Estructura no válida",
        ["title.addChild"] = "Agregar elemento hijo",
        ["msg.structuralNotEditable"] = "Los nodos estructurales html, head y body no se editan directamente. Use Documento > Propiedades para el idioma y el título.",
        ["title.documentStructure"] = "Estructura del documento",
        ["title.editElement"] = "Editar elemento",
        ["msg.structuralNotDelete"] = "No se pueden eliminar los nodos estructurales html, head o body.",
        ["msg.deleteConfirm"] = "¿Eliminar {0}?",
        ["title.confirmDelete"] = "Confirmar eliminación",
        ["msg.cannotMove"] = "No se puede mover más en esa dirección.",
        ["title.moveElement"] = "Mover elemento",
        ["msg.noEditableAttributes"] = "La etiqueta {0} no tiene atributos editables en este editor.",
        ["title.noAttributes"] = "Sin atributos",
        ["msg.noAttributesOnElement"] = "El elemento seleccionado no tiene atributos.",
        ["msg.copiedHtml"] = "El HTML se copió al portapapeles.",
        ["title.copyHtml"] = "Copiar HTML",
        ["dialog.previewFileName"] = "documento-actual.html",
        ["dialog.browserError"] = "No se pudo abrir la vista previa en el navegador",
        ["about.text"] = "HTMLBuilder\r\n\r\nAplicación de escritorio orientada a crear páginas HTML estructuradas, accesibles y fáciles de mantener.",
        ["button.save"] = "Guardar cambios",
        ["button.cancel"] = "Cancelar",
        ["button.close"] = "Cerrar",
        ["button.removeAttribute"] = "Quitar atributo",
        ["button.addAttribute"] = "Agregar o modificar atributo",
        ["label.htmlTag"] = "Etiqueta HTML",
        ["label.tagFields"] = "Campos de esta etiqueta",
        ["label.textContent"] = "Contenido textual",
        ["label.validAttributes"] = "Atributos válidos",
        ["label.attributeName"] = "Nombre del atributo",
        ["label.value"] = "Valor",
        ["label.documentTitle"] = "Título de la página",
        ["label.language"] = "Idioma",
        ["label.requiredSuffix"] = "{0} obligatorio",
        ["hint.noSpecialFields"] = "Esta etiqueta no requiere campos especiales. Puede añadir atributos válidos abajo.",
        ["hint.parent.none"] = "La etiqueta {0} no admite nuevos elementos hijo.",
        ["hint.parent.one"] = "La etiqueta {0} solo admite el hijo {1}.",
        ["hint.parent.many"] = "La etiqueta {0} admite {1} tipos de hijo válidos.",
        ["access.tagCombo"] = "Etiqueta HTML. Pulse F1 para obtener ayuda sobre la etiqueta seleccionada.",
        ["access.parentHint"] = "Información sobre la estructura permitida",
        ["access.textContent"] = "Contenido textual",
        ["access.tagFields"] = "Campos de la etiqueta",
        ["access.attributeList"] = "Atributos del elemento",
        ["access.attributeName"] = "Nombre del atributo. Pulse F1 para obtener ayuda sobre el atributo seleccionado.",
        ["access.attributeValue"] = "Valor del atributo",
        ["access.presetValue"] = "Valor predefinido del atributo",
        ["access.selectedAttributes"] = "Atributos del elemento seleccionado",
        ["msg.invalidTag"] = "La etiqueta seleccionada no es válida.",
        ["title.invalidTag"] = "Etiqueta no válida",
        ["msg.childNotAllowed"] = "La etiqueta {0} no se puede agregar dentro de {1}.",
        ["msg.attributeNotAllowed"] = "El atributo {0} no es válido para la etiqueta {1}.",
        ["title.attributeNotAllowed"] = "Atributo no permitido",
        ["msg.requiredField"] = "La etiqueta {0} necesita el campo {1}.",
        ["title.requiredField"] = "Campo requerido",
        ["msg.invalidMeta"] = "La etiqueta meta debe usar charset, o bien name junto con content.",
        ["title.incompleteMeta"] = "Meta incompleto",
        ["msg.anchorNeedsText"] = "La etiqueta a necesita texto visible que explique el destino.",
        ["title.requiredText"] = "Texto requerido",
        ["msg.noSelectedAttribute"] = "No hay ningún atributo seleccionado.",
        ["title.editAttribute"] = "Editar atributo",
        ["msg.tagNoAttributes"] = "La etiqueta {0} no tiene atributos editables.",
        ["msg.invalidAttributeName"] = "El nombre del atributo no es válido.",
        ["title.invalidAttribute"] = "Atributo no válido",
        ["msg.attributeNeedsValue"] = "El atributo {0} necesita un valor.",
        ["title.requiredValue"] = "Valor requerido",
        ["hint.booleanAttribute"] = "Este atributo es booleano y no necesita valor.",
        ["title.documentProperties"] = "Propiedades del documento",
        ["default.untitled"] = "Documento sin título",
        ["default.imported"] = "HTML importado",
        ["help.tag.title"] = "Ayuda de la etiqueta {0}",
        ["help.attribute.title"] = "Ayuda del atributo {0}",
        ["help.tag.access"] = "Ayuda de la etiqueta seleccionada",
        ["help.attribute.access"] = "Ayuda del atributo seleccionado",
        ["help.tag.label"] = "Etiqueta: {0}",
        ["help.attribute.label"] = "Atributo: {0}",
        ["help.what"] = "Para qué sirve:",
        ["help.accessibility"] = "Parámetros de accesibilidad habituales:",
        ["help.values"] = "Valores aceptados:",
        ["help.advice"] = "Consejo:",
        ["preferences.title"] = "Preferencias",
        ["preferences.language"] = "Idioma de la interfaz",
        ["preferences.english"] = "Inglés",
        ["preferences.spanish"] = "Español",
        ["preferences.restartless"] = "La interfaz se actualizará de inmediato.",
        ["language.title"] = "Elegir idioma",
        ["language.message"] = "Seleccione el idioma de la interfaz de HTMLBuilder.",
        ["language.english"] = "Inglés",
        ["language.spanish"] = "Español"
    };

    private static readonly Dictionary<string, string> FieldLabels = new(StringComparer.Ordinal)
    {
        ["Juego de caracteres"] = "Character set",
        ["Nombre"] = "Name",
        ["Contenido"] = "Content",
        ["Relación"] = "Relationship",
        ["Archivo o URL"] = "File or URL",
        ["Enlace o URL"] = "Link or URL",
        ["Fuente de la cita"] = "Citation source",
        ["Número inicial"] = "Starting number",
        ["Archivo o URL de la imagen"] = "Image file or URL",
        ["Texto alternativo"] = "Alternative text",
        ["Archivo multimedia"] = "Media file",
        ["Tipo MIME"] = "MIME type",
        ["Archivo de audio"] = "Audio file",
        ["Archivo de video"] = "Video file",
        ["Imagen de portada"] = "Poster image",
        ["Archivo de subtítulos"] = "Subtitle file",
        ["Tipo de pista"] = "Track kind",
        ["Idioma"] = "Language",
        ["Etiqueta visible"] = "Visible label",
        ["URL incrustada"] = "Embedded URL",
        ["Título accesible"] = "Accessible title",
        ["Ámbito del encabezado"] = "Header scope",
        ["Encabezados asociados"] = "Associated headers",
        ["Destino del formulario"] = "Form destination",
        ["Método"] = "Method",
        ["ID del control asociado"] = "Associated control ID",
        ["Tipo de campo"] = "Field type",
        ["Nombre del campo"] = "Field name",
        ["Nombre accesible"] = "Accessible name",
        ["Valor"] = "Value",
        ["Tipo de botón"] = "Button type",
        ["Fecha u hora legible por máquina"] = "Machine-readable date or time"
    };

    private static readonly Dictionary<string, string> FieldHelps = new(StringComparer.Ordinal)
    {
        ["Valor habitual: utf-8."] = "Common value: utf-8.",
        ["Ejemplos: viewport, description o author."] = "Examples: viewport, description, or author.",
        ["Valor asociado al nombre del metadato."] = "Value associated with the metadata name.",
        ["Ejemplos: stylesheet, preload o icon."] = "Examples: stylesheet, preload, or icon.",
        ["Destino del recurso enlazado."] = "Destination of the linked resource.",
        ["Destino del enlace. Ejemplo: https://ejemplo.com o contacto.html."] = "Link destination. Example: https://example.com or contact.html.",
        ["URL de la fuente original de la cita."] = "URL of the original quotation source.",
        ["Primer número de la lista si no empieza en 1."] = "First number of the list if it does not start at 1.",
        ["Ruta de la imagen."] = "Image path.",
        ["Describe la información útil de la imagen. Puede quedar vacío si es decorativa."] = "Describe the useful information in the image. It can be empty if the image is decorative.",
        ["Ruta del recurso."] = "Resource path.",
        ["Ejemplo: video/mp4, audio/mpeg o image/webp."] = "Example: video/mp4, audio/mpeg, or image/webp.",
        ["Puede usar src o añadir elementos source como hijos."] = "You can use src or add source elements as children.",
        ["Imagen mostrada antes de reproducir."] = "Image shown before playback.",
        ["Archivo WebVTT."] = "WebVTT file.",
        ["Valores: subtitles, captions, descriptions, chapters o metadata."] = "Values: subtitles, captions, descriptions, chapters, or metadata.",
        ["Código de idioma de la pista."] = "Language code for the track.",
        ["Nombre que verá la persona usuaria."] = "Name the user will see.",
        ["Dirección del contenido embebido."] = "Address of the embedded content.",
        ["Describe el contenido del marco para lectores de pantalla."] = "Describes the frame content for screen readers.",
        ["Valores: col, row, colgroup o rowgroup."] = "Values: col, row, colgroup, or rowgroup.",
        ["IDs de celdas th que describen esta celda."] = "IDs of th cells that describe this cell.",
        ["URL que recibirá los datos del formulario."] = "URL that will receive the form data.",
        ["Valores: get o post."] = "Values: get or post.",
        ["Debe coincidir con el id del input, select o textarea."] = "Must match the id of the input, select, or textarea.",
        ["Ejemplos: text, email, checkbox, radio o submit."] = "Examples: text, email, checkbox, radio, or submit.",
        ["Nombre enviado con el formulario."] = "Name submitted with the form.",
        ["Úselo si no hay una etiqueta label asociada."] = "Use it when no label element is associated.",
        ["Valor enviado si se selecciona esta opción."] = "Value submitted when this option is selected.",
        ["Valores recomendados: button, submit o reset."] = "Recommended values: button, submit, or reset.",
        ["Versión ISO de la fecha u hora visible."] = "ISO version of the visible date or time."
    };
}
